package com.example.frontend.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8F4C35)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDBD0)
val onPrimaryContainerLight = Color(0xFF723520)
val secondaryLight = Color(0xFF77574D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDBD0)
val onSecondaryContainerLight = Color(0xFF5D4036)
val tertiaryLight = Color(0xFF6A5E2F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF3E2A7)
val onTertiaryContainerLight = Color(0xFF51461A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF231917)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF231917)
val surfaceVariantLight = Color(0xFFF5DED7)
val onSurfaceVariantLight = Color(0xFF53433F)
val outlineLight = Color(0xFF85736E)
val outlineVariantLight = Color(0xFFD8C2BB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF392E2B)
val inverseOnSurfaceLight = Color(0xFFFFEDE8)
val inversePrimaryLight = Color(0xFFFFB59D)
val surfaceDimLight = Color(0xFFE8D6D1)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1ED)
val surfaceContainerLight = Color(0xFFFCEAE5)
val surfaceContainerHighLight = Color(0xFFF7E4DF)
val surfaceContainerHighestLight = Color(0xFFF1DFDA)


val primaryDark = Color(0xFFFFB59D)
val onPrimaryDark = Color(0xFF55200C)
val primaryContainerDark = Color(0xFF723520)
val onPrimaryContainerDark = Color(0xFFFFDBD0)
val secondaryDark = Color(0xFFE7BDB0)
val onSecondaryDark = Color(0xFF442A21)
val secondaryContainerDark = Color(0xFF5D4036)
val onSecondaryContainerDark = Color(0xFFFFDBD0)
val tertiaryDark = Color(0xFFD6C68D)
val onTertiaryDark = Color(0xFF393005)
val tertiaryContainerDark = Color(0xFF51461A)
val onTertiaryContainerDark = Color(0xFFF3E2A7)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A110F)
val onBackgroundDark = Color(0xFFF1DFDA)
val surfaceDark = Color(0xFF1A110F)
val onSurfaceDark = Color(0xFFF1DFDA)
val surfaceVariantDark = Color(0xFF53433F)
val onSurfaceVariantDark = Color(0xFFD8C2BB)
val outlineDark = Color(0xFFA08D87)
val outlineVariantDark = Color(0xFF53433F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF1DFDA)
val inverseOnSurfaceDark = Color(0xFF392E2B)
val inversePrimaryDark = Color(0xFF8F4C35)
val surfaceDimDark = Color(0xFF1A110F)
val surfaceBrightDark = Color(0xFF423733)
val surfaceContainerLowestDark = Color(0xFF140C0A)
val surfaceContainerLowDark = Color(0xFF231917)
val surfaceContainerDark = Color(0xFF271D1A)
val surfaceContainerHighDark = Color(0xFF322825)
val surfaceContainerHighestDark = Color(0xFF3D322F)




